### ISSUE TITLE
Cant get Raw Values out of SecretString / SecretBinary type secrets

### ISSUE THREAD

**Issue by tomweston** [enderv/go-secretmanager#1]
Hi enderv,

Great work, however, I have yet to get any correct raw value out in the console.

For SecretString type secrets I get the memory address:
eg, 0xc42034c0d0

For SecretBinary type secrets. I simply get:
`<nil>`

Any ideas as to why It won't return the raw value of the secret?

Thanks

**Comment by enderv** [comment]
yep I just ran into this too, was in a hurry and screwed it up with change
I put in last night. I'll fix it tonight when I get home, also will add the
secret binary output. changed it last night to just output the secretstring
and broke everything.

**Comment by enderv** [comment]
So don't have any binary secrets to try out but its now just outputting the full response so should work any issues let me know though.
